name: auto_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.1
  open_settings_plus: ^0.4.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.2
  provider: ^6.0.5
  shared_preferences: ^2.4.0
  flutter_mjpeg: ^2.0.4
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/car_model.glb
    - assets/top_down/
    - assets/sensors/left/
    - assets/sensors/front/
    - assets/sensors/right/
    - assets/

