name: auto_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.1
  model_viewer_plus: ^1.9.0
  open_settings_plus: ^0.4.0
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/car_model.glb
    - assets/

